services:
  pg:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "example"
    ports:
      - "5432:5432"
    networks:
      - backend
networks:
  backend:
    name: ts-express
