services:
  app:
    build:
      context: ./
    command: sh -c "npm run build && npm start"
    environment:
      - PG_URL=postgres://postgres:postgres@postgres:5432/example
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - NODE_PORT=3000
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - postgres
networks:
  postgres:
    name: ts-express
    external: true
      